title: "Elect Manisha Varma"
description: "Fredericton City Council – Ward 7, Southwood Park Lincoln"
baseurl: ""
url: ""
candidate_name: "Manisha Varma"
ward: "Ward 7 – Southwood Park Lincoln"
phone: "(506) 478-4794"
email: "vmanisha86@gmail.com"
facebook: "https://www.facebook.com/manisha.c.varma/"
formspree_id: "mojyazlz"